# Generated by Django 5.2.4 on 2025-08-12 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False, help_text='Si está activo, el usuario será forzado a cambiar su contraseña en el próximo inicio de sesión.', verbose_name='Forzar Cambio de Contraseña')),
                ('socio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.socio', verbose_name='Socio Vinculado (Legacy)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Web')),
            ],
            options={
                'verbose_name': 'Vínculo Usuario-Socio',
                'verbose_name_plural': 'Vínculos Usuario-Socio',
            },
        ),
    ]
