# Generated by Django 5.2.5 on 2025-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(db_index=True, help_text='Subdominio sin el dominio principal (ej: cajacomunalsantiago)', max_length=100, unique=True)),
                ('company_name', models.CharField(help_text='Nombre completo de la empresa', max_length=200)),
                ('short_name', models.CharField(help_text='Nombre corto para encabezados y títulos', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la configuración está activa')),
                ('email', models.EmailField(blank=True, help_text='Email principal de contacto', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono principal', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Dirección física completa', null=True)),
                ('website', models.URLField(blank=True, help_text='Sitio web oficial de la empresa', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa (recomendado: 300x100px)', null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Color principal en formato HEX (#007bff)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Color secundario en formato HEX', max_length=7)),
                ('site_title', models.CharField(help_text='Título que aparece en el navegador', max_length=100)),
                ('welcome_message', models.TextField(blank=True, help_text='Mensaje de bienvenida personalizado', null=True)),
                ('footer_text', models.TextField(blank=True, help_text='Texto adicional para el pie de página', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresas',
                'db_table': 'core_company_configuration',
                'ordering': ['company_name'],
            },
        ),
    ]
