# Generated by Django 5.2.4 on 2025-08-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo en Efectivo')),
                ('local_checks_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo en Cheques Locales')),
                ('internal_checks_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo en Cheques Propios')),
                ('reserve_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero bloqueado por encaje.', max_digits=12, verbose_name='Encaje')),
                ('other_guarantees_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Otras Garantías')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['socio', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INAH', 'INAH'), ('ACCI', 'ACCI'), ('DEAH', 'DEAH'), ('AHPA', 'AHPA'), ('NDAH', 'NDAH'), ('AHCE', 'AHCE'), ('REAH', 'REAH'), ('DBAH', 'DBAH'), ('NCAH', 'NCAH')], max_length=4, verbose_name='Tipo de Transacción')),
                ('flow', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], help_text='Ingreso (I) o Egreso (E)', max_length=1, verbose_name='Flujo')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('transaction_time', models.TimeField(verbose_name='Hora de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Efectivo')),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Post-Transacción')),
                ('description', models.CharField(max_length=255, verbose_name='Detalle')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date', '-transaction_time'],
            },
        ),
    ]
