# Generated by Django 5.2.4 on 2025-08-06 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('saldo_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cheques_locales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cheques_propios', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('encaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero bloqueado por encaje', max_digits=12)),
                ('otras_garantias', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transferencia', models.CharField(choices=[('INAH', 'INAH'), ('ACCI', 'ACCI'), ('DEAH', 'DEAH'), ('AHPA', 'AHPA'), ('NDAH', 'NDAH'), ('AHCE', 'AHCE'), ('REAH', 'REAH'), ('DBAH', 'DBAH'), ('NCAH', 'NCAH')], max_length=4)),
                ('flujo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], help_text='Ingreso (I) o Egreso (E)', max_length=1)),
                ('fecha_transferencia', models.DateField()),
                ('hora_transferencia', models.TimeField()),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('efectivo_transferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_post_transferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_transferencia', models.CharField(max_length=255)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='banking.account')),
            ],
        ),
    ]
