# Generated by Django 5.2.4 on 2025-08-13 16:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(help_text='Nombre del producto que verán los usuarios', max_length=100, verbose_name='Nombre comercial')),
                ('internal_code', models.CharField(help_text='Código único para identificación interna', max_length=20, unique=True, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('minimum_amount', models.DecimalField(decimal_places=2, help_text='Monto mínimo a prestar', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto mínimo')),
                ('maximum_amount', models.DecimalField(decimal_places=2, help_text='Monto máximo a prestar', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto máximo')),
                ('minimum_term_months', models.PositiveSmallIntegerField(help_text='Plazo mínimo en meses', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo mínimo (meses)')),
                ('maximum_term_months', models.PositiveSmallIntegerField(help_text='Plazo máximo en meses', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo máximo (meses)')),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, help_text='Tasa de interés anual en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Tasa de interés anual (%)')),
                ('amortization_type', models.CharField(choices=[('FRENCH', 'Francesa (Cuota fija)'), ('GERMAN', 'Alemana (Capital fijo)')], default='FRENCH', help_text='Sistema de amortización del crédito', max_length=10, verbose_name='Tipo de amortización')),
                ('has_life_insurance', models.BooleanField(default=True, help_text='Si el crédito incluye seguro de desgravamen', verbose_name='Incluye seguro de desgravamen')),
                ('life_insurance_rate', models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Tasa mensual del seguro de desgravamen sobre saldo', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='Tasa seguro de desgravamen (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Si el producto está disponible para simulaciones', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_products', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_credit_products', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Producto de Crédito',
                'verbose_name_plural': 'Productos de Crédito',
                'ordering': ['commercial_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto solicitado')),
                ('term_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo en meses')),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Cuota mensual calculada', max_digits=10, verbose_name='Cuota mensual')),
                ('total_interest', models.DecimalField(decimal_places=2, help_text='Total de intereses a pagar', max_digits=12, verbose_name='Total de intereses')),
                ('total_life_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total del seguro de desgravamen', max_digits=10, verbose_name='Total seguro de desgravamen')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total incluyendo capital, intereses y seguros', max_digits=12, verbose_name='Monto total a pagar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de simulación')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la simulación', null=True, verbose_name='Dirección IP')),
                ('credit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='credit_simulator.creditproduct', verbose_name='Producto de crédito')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la simulación (puede ser anónimo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_simulations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Simulación de Crédito',
                'verbose_name_plural': 'Simulaciones de Crédito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(verbose_name='Número de cuota')),
                ('principal_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago a capital')),
                ('interest_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago de interés')),
                ('life_insurance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pago seguro de desgravamen')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago total')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_entries', to='credit_simulator.creditsimulation', verbose_name='Simulación')),
            ],
            options={
                'verbose_name': 'Entrada de Tabla de Amortización',
                'verbose_name_plural': 'Entradas de Tabla de Amortización',
                'ordering': ['simulation', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='creditproduct',
            index=models.Index(fields=['is_active'], name='credit_simu_is_acti_073135_idx'),
        ),
        migrations.AddIndex(
            model_name='creditproduct',
            index=models.Index(fields=['minimum_amount', 'maximum_amount'], name='credit_simu_minimum_654230_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsimulation',
            index=models.Index(fields=['user', '-created_at'], name='credit_simu_user_id_d92635_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsimulation',
            index=models.Index(fields=['credit_product', '-created_at'], name='credit_simu_credit__07c7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='amortizationscheduleentry',
            index=models.Index(fields=['simulation', 'installment_number'], name='credit_simu_simulat_ceb803_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='amortizationscheduleentry',
            unique_together={('simulation', 'installment_number')},
        ),
    ]
