# Generated by Django 5.2.4 on 2025-08-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahorrohistorial',
            options={'managed': False, 'verbose_name': 'Historial de Ahorro', 'verbose_name_plural': 'Historiales de Ahorro'},
        ),
    ]
